build: fix C23 build failure in HX_isascii
Rewrite ``HX_isascii`` to workaround the removal of ``isascii`` from
POSIX.1-2008, and a subsequent build failure when using ``make
CC=gcc-15 CFLAGS=-std=c23``.

```
In function 'HX_isascii':
44:16: error: implicit declaration of function 'isascii' [-Wimplicit-function-declaration]
   44 |         return isascii(c);
```