include: add missing includes to string.h
When compiling in stricter mode with -std=c99, this can be observed:

../include/libHX/string.h:81:2: error: "ssize_t" undeclared
(first use in this function)
../include/libHX/string.h:81:2: note: each undeclared identifier is
reported only once for each function it appears in