build: make sure off_t is defined in mingw32
When using -std=c99, the mingw runtime will not define off_t.
Build error was:

	uxcompat.h:96:50: error: unknown type name "off_t"